Entrega Trabajo 1
Danieljara23/challenge-1 pull request #1
Opened 2023-08-23 12:03 UTC by Juango21

# Entrega página para retroalimentación
 Pagina de 3 secciones

2023-08-23 12:20 UTC, Danieljara23 requested changes

2023-08-23 12:20 UTC, Danieljara23 commented on index.html
> +
Eliminar estos espacios

2023-08-23 12:20 UTC, Danieljara23 commented on index.html
> +  <!-- PARTE FINAL JUAN JOSE RAMIREZ  -->
Ojo con estos comentarios

2023-08-23 12:20 UTC, Danieljara23 commented on style.css
> +  }
Este código lo están repitiendo varias veces. Creen una sola clase y se la aplican a todas las 3 cajas.

2023-08-23 12:20 UTC, Danieljara23 commented on index.html
> +      <div class="Marketing2">
Los nombres de las clases deben ser todos en minúscula

2023-08-23 12:20 UTC, Danieljara23 commented on index.html
> +      <div class="Development">
Los nombres de las clases deben ser todos en minúscula

2023-08-23 12:20 UTC, Danieljara23 commented on index.html
> +      <div class="button-link">
Cuidado con el spanglish

2023-08-23 17:39 UTC, Danieljara23 requested changes

2023-08-23 17:40 UTC, Danieljara23 requested changes

2023-08-23 17:40 UTC, Danieljara23 commented on homero compu.png
Esta imagen se ve pixelada

2023-08-25 00:30 UTC, goodlullaby commented on index.html
> +  <!-- PARTE FINAL JUAN JOSE RAMIREZ  -->
Listo

2023-08-25 00:30 UTC, goodlullaby commented on style.css
> +  }
Listo

2023-08-25 00:31 UTC, goodlullaby commented on index.html
> +      <div class="Marketing2">
Listo

2023-08-25 00:31 UTC, goodlullaby commented on index.html
> +      <div class="Development">
Listo

2023-08-25 00:31 UTC, goodlullaby commented on index.html
> +      <div class="Marketing1">
Listo

2023-08-25 00:31 UTC, goodlullaby commented on index.html
> +      <div class="button-link">
Listo

2024-03-04 01:00 UTC, closed without merging