Victoria Rosenstiehl y Angélica Agudelo
Danieljara23/challenge-1 pull request #3
Opened 2023-08-23 21:49 UTC by Vickkkk24

# Actividad evaluativa 1

2023-08-23 23:34 UTC, Danieljara23 requested changes

2023-08-23 23:34 UTC, Danieljara23 commented on index.html
> +  <div class="Logo-español">
Los nombres de las clases deben ser totalmente en minúscula (Es una buena práctica)

2023-08-23 23:34 UTC, Danieljara23 commented on index.html
> +        <p class="mini-cajita"> by <span style="color: black;"><strong> Vick & Angie</strong></span></p>
Procuremos evitar inline-styles a no ser que sea estrictamente necesario
```suggestion
        <p class="mini-cajita"> by <span><strong> Vick & Angie</strong></span></p>
```

2023-08-23 23:34 UTC, Danieljara23 commented on style.css
> +
Podemos eliminar este espacio
```suggestion
```

2023-08-23 23:34 UTC, Danieljara23 commented on style.css
> +}
Si se dan cuenta, están repitiendo todo este código para los 3 contenedores. Yo sugeriría que le apliquen la misma clase a todos los 3 contenedores y así evitan la repetición.

2023-08-23 23:34 UTC, Danieljara23 commented on style.css
> +.boton-3 {
Lo mismo en los botones. Hay código que se repite. Pueden reutilizar el código unificando todo en una sola clase

2023-08-23 23:34 UTC, Danieljara23 commented on style.css
> +}
Aplica lo mismo de repetir código. Pueden utilizar una misma clase para todos los 3 `cardinfo`

2023-08-24 00:21 UTC, Vickkkk24 commented on style.css
> +.boton-3 {
Hola, profe, hice el cambio que sugirió, pero solo con la clase "boton-2" que es la que se encarga de darle orientación y forma a los botones, sin embargo no veo cómo puedo hacer lo mismo con la clase "boton-fake#" porque necesito que cada botón cambie a un color distinto cuando se pase el puntero por ahí y eso lo logré haciendo 3 clases de boton-fake y asignarle un color a cada una por separado. ¿Está bien si lo dejo así o hay otra manera?

2024-03-04 01:00 UTC, closed without merging